# Generated by Django 3.1.1 on 2020-09-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytoken',
            name='expiry_date',
            field=models.DateTimeField(),
        ),
    ]
